version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
resolve_s3 = true
confirm_changeset = true


[default.global.parameters]
region = "us-east-1"
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws"
resolve_s3 = true
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true
confirm_changeset = true


[staging.global.parameters]
region = "us-east-1"
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_bucket = "aws-sam-cli-managed-production-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
